apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: capacitor
    app.kubernetes.io/managed-by: Flux
    app.kubernetes.io/name: onechart
    kustomize.toolkit.fluxcd.io/name: capacitor
    kustomize.toolkit.fluxcd.io/namespace: capacitor
  name: capacitor
  namespace: capacitor
spec:
  ports:
  - name: http
    port: 9000
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: capacitor
    app.kubernetes.io/name: onechart
  sessionAffinity: None
  type: LoadBalancer