apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: grafana
  namespace: flux-system  # Ensure this matches your Flux namespace
spec:
  interval: 1h
  url: https://grafana.github.io/helm-charts