apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  interval: 1h
  chart:
    spec:
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana
      version: 2.9.10
  values:
    loki:
      enabled: true
      isDefault: true
      persistence:
        enabled: true
        size: 10Gi
      service:
        type: LoadBalancer
        port: 3100
    promtail:
      enabled: true
      config:
        clients:
          - url: http://loki-stack:3100/loki/api/v1/push
    grafana:
      enabled: false  # Already deployed separately
    alertmanager:
      enabled: false
    fluent-bit:
      enabled: false
