apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
  labels:
    app: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: loki-storage
  hostPath:
    path: /mnt/data/loki  # Change this path if using a different storage backend
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-pvc
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: loki-storage