apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-export-1-loki-minio
  namespace: monitoring
  labels:
    app: minio
    release: loki
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/export-1-loki-minio
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-export-0-loki-minio
  namespace: monitoring
  labels:
    app: minio
    release: loki
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/export-0-loki-minio
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-storage-loki-0
  namespace: monitoring
  labels:
    app: loki
    release: loki
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/storage-loki-0
  volumeMode: Filesystem
